from infos.models import *
from custom_auth.models import *

CustomUser.objects.create_superuser("wassel2005@gmail.com", "", 4)
CustomUser.objects.create_user("danieladorno75@gmail.com", CustomUser.objects.make_random_password(128), 1, "Daniel", "Adorno")
CustomUser.objects.create_user("adornoyann990@gmail.com", CustomUser.objects.make_random_password(128), 1, "Yann", "Adorno")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Antoine", "Akhtar")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Ronald", "Blarasin")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Corentin", "Boussac")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Pacômme", "Brittes")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Olympe", "Cabande")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Quentin", "Cardona")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Virgile", "Ceaux")
CustomUser.objects.create_user("hugo.2003@gmail.coma", CustomUser.objects.make_random_password(128), 1, "Hugo", "Chen")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Corentin", "De Rette")
CustomUser.objects.create_user("amir.djelidi.pro@gmail.com", CustomUser.objects.make_random_password(128), 1, "Amir", "Djelidi")
CustomUser.objects.create_user("inelga75@gmail.com", CustomUser.objects.make_random_password(128), 1, "Inès", "El Garouani")
CustomUser.objects.create_user("e.yslem@outlook.fr", CustomUser.objects.make_random_password(128), 1, "Yslem", "Essid")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Félix", "Gousset")
CustomUser.objects.create_user("david.khersis@gmail.com", CustomUser.objects.make_random_password(128), 1, "David", "Khersis")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Grégoire", "Lan Tim")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Isidore", "Lieutaud")
CustomUser.objects.create_user("enzo.lobies@free.fr", CustomUser.objects.make_random_password(128), 1, "Enzo", "Lobies")
CustomUser.objects.create_user("anae.mellini@laposte.fr", CustomUser.objects.make_random_password(128), 1, "Anaé", "Mellini")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Farès", "Mestre")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Alice", "Oliver")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Ulysse", "Oval")
CustomUser.objects.create_user("oscar.pecoud-gatti@hotmail.com", CustomUser.objects.make_random_password(128), 1, "Oscar", "Pécoud Gatti")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Sonia", "Phu")
CustomUser.objects.create_user("marionpiault@yahoo.fr", CustomUser.objects.make_random_password(128), 1, "Marion", "Piault")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Thomas", "Touffait")
CustomUser.objects.create_user("audreytran03@gmail.com", CustomUser.objects.make_random_password(128), 1, "Audray", "Tran")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Carla", "Villaume")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Victor", "Vitri Demay")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Malèna", "Vivacqua")
CustomUser.objects.create_user("", CustomUser.objects.make_random_password(128), 1, "Patricia", "Zhou")