from infos.models import *
from custom_auth.models import *

CustomUser.objects.create_user("danieladorno75@gmail.com", CustomUser.objects.make_random_password(128), 1, "Daniel", "Adorno")
CustomUser.objects.create_user("adornoyann990@gmail.com", CustomUser.objects.make_random_password(128), 1, "Yann", "Adorno")
CustomUser.objects.create_user("antoineakhtar@gmail.com", CustomUser.objects.make_random_password(128), 2, "Antoine", "Akhtar")
CustomUser.objects.create_user("roro.blrs@gmail.com", CustomUser.objects.make_random_password(128), 3, "Ronald", "Blarasin")
CustomUser.objects.create_user("corentinboussac@gmail.com", CustomUser.objects.make_random_password(128), 5, "Corentin", "Boussac")
CustomUser.objects.create_user("luis.pacomme@hotmail.fr", CustomUser.objects.make_random_password(128), 3, "Pacômme", "Brittes")
CustomUser.objects.create_user("olympe.czbande@gmail.com", CustomUser.objects.make_random_password(128), 6, "Olympe", "Cabande")
CustomUser.objects.create_user("cardona.sorin@orange.fr", CustomUser.objects.make_random_password(128), 7, "Quentin", "Cardona")
CustomUser.objects.create_user("Virgile.ceaux@gmail.com", CustomUser.objects.make_random_password(128), 3, "Virgile", "Ceaux")
CustomUser.objects.create_user("hugo.2003@gmail.coma", CustomUser.objects.make_random_password(128), 8, "Hugo", "Chen")
CustomUser.objects.create_user("corentin.derette@yahoo.fr", CustomUser.objects.make_random_password(128), 9, "Corentin", "De Rette")
CustomUser.objects.create_user("amir.djelidi.pro@gmail.com", CustomUser.objects.make_random_password(128), 10, "Amir", "Djelidi")
CustomUser.objects.create_user("inelga75@gmail.com", CustomUser.objects.make_random_password(128), 11, "Inès", "El Garouani")
CustomUser.objects.create_user("e.yslem@outlook.fr", CustomUser.objects.make_random_password(128), 15, "Yslem", "Essid")
CustomUser.objects.create_user("felixgousset@gmail.com", CustomUser.objects.make_random_password(128), 15, "Félix", "Gousset")
CustomUser.objects.create_user("david.khersis@gmail.com", CustomUser.objects.make_random_password(128), 11, "David", "Khersis")
CustomUser.objects.create_user("gregoire.lantim@free.fr", CustomUser.objects.make_random_password(128), 17, "Grégoire", "Lan Tim")
CustomUser.objects.create_user("Isidore.lieutaud", CustomUser.objects.make_random_password(128), 11, "Isidore", "Lieutaud")
CustomUser.objects.create_user("enzo.lobies@free.fr", CustomUser.objects.make_random_password(128), 11, "Enzo", "Lobies")
CustomUser.objects.create_user("anae.mellini@laposte.fr", CustomUser.objects.make_random_password(128), 12, "Anaé", "Mellini")
CustomUser.objects.create_user("belokuikuini@outlook.fr", CustomUser.objects.make_random_password(128), 14, "Farès", "Mestre")
CustomUser.objects.create_user("alice.oliver@gmail.com", CustomUser.objects.make_random_password(128), 11, "Alice", "Oliver")
CustomUser.objects.create_user("ulysso@gmail.com", CustomUser.objects.make_random_password(128), 16, "Ulysse", "Oval")
CustomUser.objects.create_user("oscar.pecoud-gatti@hotmail.com", CustomUser.objects.make_random_password(128), 13, "Oscar", "Pécoud Gatti")
CustomUser.objects.create_user("phusonia21@gmail.com", CustomUser.objects.make_random_password(128), 16, "Sonia", "Phu")
CustomUser.objects.create_user("marionpiault@yahoo.fr", CustomUser.objects.make_random_password(128), 21, "Marion", "Piault")
CustomUser.objects.create_user("touffait.thomas@yahoo.com", CustomUser.objects.make_random_password(128), 19, "Thomas", "Touffait")
CustomUser.objects.create_user("audreytran03@gmail.com", CustomUser.objects.make_random_password(128), 22, "Audray", "Tran")
CustomUser.objects.create_user("carla.villaume@gmail.com", CustomUser.objects.make_random_password(128), 12, "Carla", "Villaume")
CustomUser.objects.create_user("victor.vitrydemey@gmail.com", CustomUser.objects.make_random_password(128), 23, "Victor", "Vitri Demay")
CustomUser.objects.create_user("maloutsevivacqua@gmail.com", CustomUser.objects.make_random_password(128), 20, "Malèna", "Vivacqua")
CustomUser.objects.create_user("patricia_zh17@outlook.com", CustomUser.objects.make_random_password(128), 18, "Patricia", "Zhou")